### ISSUE TITLE
Question of learning time

### ISSUE THREAD

**Issue by Hen-jo** [XinhaoMei/WavCaps#10]
Could you please provide a rough estimate of the time it takes to complete one epoch with a batch size of 32? I would like to verify if my training setup is configured properly.

**Comment by XinhaoMei** [comment]
Hi, 
I think the running time depends on your device. 
In our case, we run audio-text retrieval on a single A100-80GB with a batch size of 128. The HTSAT model takes about 35 minutes for one epoch, while the CNN model tasks about 1 hour for one epoch.
