### ISSUE TITLE
pretrained audio_encoder

### ISSUE THREAD

**Issue by song16** [XinhaoMei/WavCaps#11]
Hi, thank you for sharing this wonderful project. I want to know how the pretrained audio encoders model is trained. I want to change the feature dimension and network structure based on your code

**Comment by XinhaoMei** [comment]
Hi, thanks for your interests!

For the audio encoder, we use PANNs and HTSAT trained with an audio tagging task. You could refer to [PANNs](https://github.com/qiuqiangkong/audioset_tagging_cnn) and [HTSAT](https://github.com/RetroCirce/HTS-Audio-Transformer) for details. In our code, you can find them under the `models` directory.
