### ISSUE TITLE
AttributeError: 'SequentialSampler' object has no attribute 'set_epoch'

### ISSUE THREAD

**Issue by jwang1993** [XinhaoMei/WavCaps#12]
Hi, thank you for sharing this wonderful project. When I run pretrain.py, I find a bug like "AttributeError: 'SequentialSampler' object has no attribute 'set_epoch'". Why does this occur? Can you provide the “requirements.txt” file,  and I would like to know version of all packages. 
Thanks.

**Comment by XinhaoMei** [comment]
Hi, 

Sorry, I didn't encounter this error before. 
I have uploaded my conda env for this project [here](https://github.com/XinhaoMei/WavCaps/blob/master/retrieval/work.yaml).
Thanks for your interests!

**Comment by jwang1993** [comment]
Are you running on DDP? My startup command is as follows

torchrun \
   --standalone \
  --nnodes=$nnodes \
  --nproc_per_node=$nproc_per_node \
  pretrain.py \

**Comment by XinhaoMei** [comment]
Oh, yes, this might be the problem. I ran it on a single A100.
You could set bucket to false to use a default sampler.
