### ISSUE TITLE
Alignment between audio and text

### ISSUE THREAD

**Issue by Ming-er** [XinhaoMei/WavCaps#15]
Hi, I find a problem about the pretrained models. Although clip-level audio features are well aligned with text features, the fine-grained alignment between frame-level audio features and text features is not established since I directly test the pretrained models on DESED (a dataset used for sound event detection) validation dataset and find that all frame-level embeddings share high similarity with label embeddings instead of some specific frames where the corresponding sound event exactly take place. I think the possible reason might be the global avg pool is used in the audio encoder to aggregate local features (instead of attention pool used in the original CLIP), so I wonder if you have tried different pooling method?

**Comment by XinhaoMei** [comment]
Hi, 

Yes, the global pooing is not a good option. I didn't try other methods. I think this [paper](https://ieeexplore.ieee.org/abstract/document/10097117) investigated this problem.

**Comment by Ming-er** [comment]
Thank you for your reply, I'll read it.
