### ISSUE TITLE
To reproduce zero-shot audio classification result

### ISSUE THREAD

**Issue by Ming-er** [XinhaoMei/WavCaps#17]
Dear author, I want to pretrain from scratch and reproduce the zero-shot audio classification result. Should I use the 'blacklist_exclude_ub8k_esc50_vggsound.json' as the blacklist file, and use the 'retrieval/settings/pretrain.yaml' as the configuration?

**Comment by XinhaoMei** [comment]
Yes. In the blacklist file, the id of audio clips from AudioSet is stored with ".wav", do necessary modification if you data format is flac. In addition, the script is only tested for single-card training, set `bucket` to false in `pretrain_dataloader` if you want to use multi-card training.

**Comment by Ming-er** [comment]
Thank you for your advice, I will try it! If I have any more problems, I will ask you again!

**Comment by Ming-er** [comment]
Dear author, sorry to bother you again. In Line 39-45 of file "retrieval/data_handling/pretrain_dataset.py", it requires the keys "duration" and "id" in the train.json file of Clotho dataset. However, I cannot find them in the provided json file. What should I do?

**Comment by XinhaoMei** [comment]
Hi, 'id' is the id of the waveform in FreeSound which will be used for blacklist, and the 'duration' is the length of the audio in second. I have updated new json files of Clotho that contain these two keys.

**Comment by Ming-er** [comment]
It really helps, thanks !
