### ISSUE TITLE
Question audio caption evaluating

### ISSUE THREAD

**Issue by chenxinglili** [XinhaoMei/WavCaps#19]
I'm testing the performance of audio caption.
I encountered some problems when using [eval_metrics.py] in the caption folder.
For example, "image","image_id" does not exist in self.dataset, etc.

I guess you have modified pycocotools and pycocoevalcap. Can you provide the modified evaluation tools?

**Comment by XinhaoMei** [comment]
Hi, we didn't modify it.
Where did you get the coco_caption evaluation tool? You could copy them from my previous repoistories. https://github.com/XinhaoMei/ACT/tree/main/coco_caption

**Comment by chenxinglili** [comment]
Thanks! 
The evaluation tool you provided works well.
I just "pip install pycocotools pycocoevalcap" directly. I found that there is indeed something different.

There is another small question:
By testing, the result obtained is a decimal (like 0.186). The results in the paper are in the dozens.
Have you multiplied by 100 or there is something wrong with my test?

Besides, I found SPICE can not work well with long caption. Have you ever encountered such a problem?

**Comment by XinhaoMei** [comment]
> Thanks! The evaluation tool you provided works well. I just "pip install pycocotools pycocoevalcap" directly. I found that there is indeed something different.
> 
> There is another small question: By testing, the result obtained is a decimal (like 0.186). The results in the paper are in the dozens. Have you multiplied by 100 or there is something wrong with my test?
> 
> Besides, I found SPICE can not work well with long caption. Have you ever encountered such a problem?

Yes, it's percentage in the paper.

For the second probelm, could you please give more details about it?

**Comment by chenxinglili** [comment]
Sorry for the late.
The docker environment was deleted and I'm in the process of recovering it.
Maybe several days later I can reproduce the error and post it.

**Comment by chenxinglili** [comment]
Hi, i am back.
The log is here:
-----------------------------------------------------------------------------------------
computing SPICE score...
Parsing reference captions
Parsing test captions
Initiating Stanford parsing pipeline
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... 
done [0.4 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.0 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.6 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.4 sec].
Threads( StanfordCoreNLP ) [56.988 seconds]
Error: Could not cache item to WavCaps/captioning/coco_caption/pycocoevalcap/spice/cache with key:
"the audio depicts a scene where water is being poured into a sink it could also involve the sound of someone showering with running water accompanied by the resonant echo of the water hitting the tub the scene is likely taking place in a bathroom such as a home or public facility in the background there 's the consistent sound of a machine running potentially related to the water 's displacement this combination of water and mechanical noises creates an audio scene that evokes a sense of practicality and activity"
Caption may be too long
-----------------------------------------------------------------------------------------

This may be because the generated description is too long.

**Comment by XinhaoMei** [comment]
> ## Hi, i am back.
> The log is here:
> ## computing SPICE score...
> Parsing reference captions
> Parsing test captions
> Initiating Stanford parsing pipeline
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
> [main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
> [main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ...
> done [0.4 sec].
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
> [main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
> Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.0 sec].
> Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1.6 sec].
> Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.4 sec].
> Threads( StanfordCoreNLP ) [56.988 seconds]
> Error: Could not cache item to WavCaps/captioning/coco_caption/pycocoevalcap/spice/cache with key:
> "the audio depicts a scene where water is being poured into a sink it could also involve the sound of someone showering with running water accompanied by the resonant echo of the water hitting the tub the scene is likely taking place in a bathroom such as a home or public facility in the background there 's the consistent sound of a machine running potentially related to the water 's displacement this combination of water and mechanical noises creates an audio scene that evokes a sense of practicality and activity"
> Caption may be too long
> This may be because the generated description is too long.

Haha, interesting. I never encountered this before. 

Yes, I also think the reason might be the caption is too long. 

Can I ask that is this generated by a LLM?

**Comment by chenxinglili** [comment]
Yep, the result is generated by an open-sourced multi-model llm, buboGPT.
 https://github.com/magic-research/bubogpt
I tested the audio caption abilities of buboGPT, but the performance did not meet expectations. 
Also wordy!

**Comment by XinhaoMei** [comment]
> Yep, the result is generated by an open-sourced multi-model llm, buboGPT. https://github.com/magic-research/bubogpt I tested the audio caption abilities of buboGPT, but the performance did not meet expectations. Also wordy!

Yes, most current LLMs still cannot do well in audio understanding.

**Comment by chenxinglili** [comment]
But, the latest LLM-based paper achieves a new SOTA results,
NExT-GPT: Any-to-Any Multimodal LLM

**Comment by XinhaoMei** [comment]
> But, the latest LLM-based paper achieves a new SOTA results, NExT-GPT: Any-to-Any Multimodal LLM

Looks interesting. Have you tried their demo?

**Comment by chenxinglili** [comment]
Haven't yet.
it has become a trend.

**Comment by XinhaoMei** [comment]
> Haven't yet. it has become a trend.

Have tried some examples using their demo for audio captioning. It seems the performance is not as good as reported in the paper. Maybe I didn't use the correct prompt😂

**Comment by chenxinglili** [comment]
Hi,
Do you have the caption results of your ACT model on the audiocaps testset? 
I want to compare the difference between the results produced by the ACT and the llm-based model.

**Comment by chenxinglili** [comment]
Hi, can I add you on WeChat?

**Comment by XinhaoMei** [comment]
> Hi, can I add you on WeChat?

Of course, my id is mxh511185064.
