### ISSUE TITLE
Blacklist Metadata

### ISSUE THREAD

**Issue by alefiury** [XinhaoMei/WavCaps#21]
Dear Author,

First and foremost, congratulations on your commendable work!

Now, onto the inquiry.

In the directory "blacklist" of the dataset there are 3 json files: "blacklist_exclude_all_ac.json", "blacklist_exclude_test_ac.json" and "blacklist_exclude_ub8k_esc50_vggsound.json". 

I'd like to confirm my understanding of the file removal process from the WavCaps dataset as follows:

- "blacklist_exclude_all_ac.json" excludes ALL data from audiocaps (overlaping with AudioSet) and Clotho (overlaping with FreeSound)
- "blacklist_exclude_test_ac.json" excludes ALL test (or maybe ALL test AND validation data) data from audiocaps (overlaping with AudioSet) and Clotho (overlaping with FreeSound)
- "blacklist_exclude_ub8k_esc50_vggsound.json" excludes ALL data from UrbanSound8K (overlaping with FreeSound), ESC-50 (overlaping with FreeSound) and VGGSound (overlaping with AudioSet)

Is this intrepretation correct?

**Comment by XinhaoMei** [comment]
Hey, yes, that's absolutely correct!
