### ISSUE TITLE
Considerations on issue with mute sample (592228)

### ISSUE THREAD

**Issue by ozerodb** [XinhaoMei/WavCaps#23]
Hello, thank you very much for your work on this dataset! It's honestly incredible🙏🏻

I wanted to ask though if you ever considered removing (either in the metadata or the blacklists) samples with nothing (only silence) in them, when building the dataset.
 
To be precise, I don't know how many mute samples there are, and I would argue that they might actually be useful during training, but I have had issues with one in particular:

[592228](https://freesound.org/people/MissloonerVoiceOver255/sounds/592228/)

Even if the file is at 1Hz (hence very small on disk), when loading it with librosa it would cause my entire training to crash without any particular error, because `librosa.load()` was trying to resample it to the given sampling rate (in my case 16khz), but the audio is **200** hours long, thus causing the underlying memory allocation to fail (around 85gb of contiguous memory😅).

Given the absence of a real error message (except a generic `RuntimeError: DataLoader worker (pid(s) ***) exited unexpectedly`), finding the issue wasn't as easy as solving it (I simply specified the `duration` parameter in `librosa.load()`, so that the function doesn't try to load the entire file), but I wanted to ask you anyway if anything of the sort happened to you (or someone else) when dealing with the dataset.

**Comment by XinhaoMei** [comment]
Hello, thanks for your interests.

Did you use our provided data? I think we have removed audio clips whose duration is less than 1 second in WavCaps,

**Comment by ozerodb** [comment]
Hello, thank you for the reply, it's good to know that short clips have been removed🙏🏻

Regarding the issue, yes, I used the `.flac` version hosted on HuggingFace.

I am not referring to short audio clips. As mentioned in my original comment I found one [(592228)](https://freesound.org/people/MissloonerVoiceOver255/sounds/592228/) that is **200 hours** long but doesn't have anything in it.

It's possible to replicate the issue as follows:
```bash
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> base_path = "data/WavCaps/Zip_files/FreeSound/mnt/fast/nobackup/scratch4weeks/xm00178/WavCaps/data/waveforms/FreeSound_flac"
>>> nothing_sample = os.path.join(base_path, "592228.flac")
>>> os.path.exists(nothing_sample)
True
>>> import librosa
>>> audio, sr  = librosa.load(nothing_sample, sr=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dbonaccorsi/miniconda3/lib/python3.11/site-packages/librosa/core/audio.py", line 175, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonaccorsi/miniconda3/lib/python3.11/site-packages/librosa/core/audio.py", line 221, in __soundfile_load
    y = sf_desc.read(frames=frame_duration, dtype=dtype, always_2d=False).T
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonaccorsi/miniconda3/lib/python3.11/site-packages/soundfile.py", line 891, in read
    out = self._create_empty_array(frames, always_2d, dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonaccorsi/miniconda3/lib/python3.11/site-packages/soundfile.py", line 1323, in _create_empty_array
    return np.empty(shape, dtype, order='C')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 85.8 GiB for an array with shape (23040000000,) and data type float32
>>> import numpy as np
>>> audio, sr  = librosa.load(nothing_sample, sr=None, dtype=np.int16)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dbonaccorsi/miniconda3/lib/python3.11/site-packages/librosa/core/audio.py", line 175, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonaccorsi/miniconda3/lib/python3.11/site-packages/librosa/core/audio.py", line 221, in __soundfile_load
    y = sf_desc.read(frames=frame_duration, dtype=dtype, always_2d=False).T
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonaccorsi/miniconda3/lib/python3.11/site-packages/soundfile.py", line 891, in read
    out = self._create_empty_array(frames, always_2d, dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dbonaccorsi/miniconda3/lib/python3.11/site-packages/soundfile.py", line 1323, in _create_empty_array
    return np.empty(shape, dtype, order='C')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 42.9 GiB for an array with shape (23040000000,) and data type int16
```
In my case, even halving the precision wouldn't make the sample fit in memory

**Comment by XinhaoMei** [comment]
Thanks for clarifying.

I am sorry. I didn't encounter this during training.

There are some long audio clips from FreeSound.  Maybe you can directly skip them. 😂  There is a 'duration' key in the json files.

**Comment by ozerodb** [comment]
Yes, thank you for the suggestion.
As mentioned I ended up limiting the amount of samples loaded by simply specifying `librosa.load(..., duration=<my_max_duration>)`, so I am still using that clip but the error is gone.
