### ISSUE TITLE
about Pretraining Model on wavcaps  for audio captioning

### ISSUE THREAD

**Issue by hello-xiaow** [XinhaoMei/WavCaps#24]
Thank you for providing such a wonderful job！ I couldn't find the audiocaptioning pretraining model on Wavcaps. [CNN14-BART baseline,HTSAT-BART baseline],Can you provide it?

**Comment by XinhaoMei** [comment]
Hi, here is the link. https://drive.google.com/drive/folders/1M39SJe550oap1euLIt5YaMdZVQ9C8wKI

**Comment by hello-xiaow** [comment]
> Hi, here is the link. https://drive.google.com/drive/folders/1M39SJe550oap1euLIt5YaMdZVQ9C8wKI

Thank you for your reply. Are the models you provided fine-tuned on the audiocap and clotho datasets? Do you have a pre trained model on Wavcaps？

**Comment by XinhaoMei** [comment]
> > Hi, here is the link. https://drive.google.com/drive/folders/1M39SJe550oap1euLIt5YaMdZVQ9C8wKI
> 
> Thank you for your reply. Are the models you provided fine-tuned on the audiocap and clotho datasets? Do you have a pre trained model on Wavcaps？

Hello,

For audio captioning, these baselines reported in the paper were only trained on AudioCaps or Clotho.

At this time, we didn't provide the checkpoints pretrained on WavCaps. Very sorry about this.

**Comment by hello-xiaow** [comment]
> > > Hi, here is the link. https://drive.google.com/drive/folders/1M39SJe550oap1euLIt5YaMdZVQ9C8wKI
> > 
> > 
> > Thank you for your reply. Are the models you provided fine-tuned on the audiocap and clotho datasets? Do you have a pre trained model on Wavcaps？
> 
> Hello,
> 
> For audio captioning, these baselines reported in the paper were only trained on AudioCaps or Clotho.
> 
> At this time, we didn't provide the checkpoints pretrained on WavCaps. Very sorry about this.


Thank you for your reply
