### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by Ming-er** [XinhaoMei/WavCaps#25]
Sorry to bother you again, I want to reproduce the results of audio-text retrieval, however, I always got 2%-3% lower outcome compared to the table in your paper, so i wonder if there any training log files I can refer to?

**Comment by XinhaoMei** [comment]
[output.log](https://github.com/XinhaoMei/WavCaps/files/13699180/output.log)

Please find attached log file for HTSAT-BERT-PT model.

**Comment by Ming-er** [comment]
It seems that there are much better results in your provided log file than in the published paper ?

**Comment by XinhaoMei** [comment]
> It seems that there are much better results in your provided log file than in the published paper ?

No, only the last three results were evaluated in test sets of AudioCaps and Clotho using checkpoints. Others were validation results.

**Comment by Ming-er** [comment]
oh, I got it. I can only reproduce it with the distributed mode on 2 RTX 3090s, and I change 'librosa.load' to 'torchlibrosa.load' for loading audios since the former is cpu intensive and much slower. Do you think these changes will affect the performance?

**Comment by XinhaoMei** [comment]
> oh, I got it. I can only reproduce it with the distributed mode on 2 RTX 3090s, and I change 'librosa.load' to 'torchlibrosa.load' for loading audios since the former is cpu intensive and much slower. Do you think these changes will affect the performance?

I guess it might be caused by the distributed training.

**Comment by Ming-er** [comment]
thank you for your advice, I will try it on other devices
