### ISSUE TITLE
Is the unprocessed data availiable?

### ISSUE THREAD

**Issue by BingliangLi** [XinhaoMei/WavCaps#27]
Hi, I'm trying to get some 44.1 kHz audio for my model, I noticed the data is all mono 32k Hz, I wonder do you still have the original files(can be converted to flac to reduce size but please keep the sr to 44.1 kHz and number of channels), and could you please share them? thank you verrrrrrrrry much!
I do believe the next step for audio is stereo and high resolution, similar to those guys did in computer vision :)

**Comment by XinhaoMei** [comment]
Sorry for my late reply. Unforturnately, we didn't keep the origianl audio clips. Maybe you could try to download them from the original website.
