### ISSUE TITLE
Requirements for more pretrained weights

### ISSUE THREAD

**Issue by Ming-er** [XinhaoMei/WavCaps#8]
Hi, thanks for your brilliant work. I want to know if there are any plans to release more pretrained weights, such as CNN14-BERT-PT ?

**Comment by XinhaoMei** [comment]
Hi, no problem. I will upload it as soon as possible!

**Comment by XinhaoMei** [comment]
Hi, CNN14-BERT-PT has been uploaded to Google Drive.

**Comment by Ming-er** [comment]
Many thanks. I will try it right now.
