### ISSUE TITLE
How can I directly use your pretrained model of audio caption  to test my audio cases without finetuning?

### ISSUE THREAD

**Issue by joewale** [XinhaoMei/WavCaps#9]
Hi, thank you for sharing this wonderful project. How can I directly use your pretrained model of audio caption  to test my audio cases without finetuning?

**Comment by XinhaoMei** [comment]
Hi, I have uploaded an example [test script](https://github.com/XinhaoMei/WavCaps/blob/master/captioning/test.py). I hope this is helpful!

**Comment by joewale** [comment]
Thank you a lot !  I have tested my case.
